### ISSUE TITLE
Getting timed out message from socket on subscribe or presence

### ISSUE THREAD

**Issue by foobargeez** [centrifugal/centrifuge-mobile#9]
I am intermittently noticing timed out message when I do subscribe or presence and when in this state, the client never reconnects. I noticed this in go-mobile client and the only way to get out of this state is to terminate the app and relaunch it, so the socket connection gets established successfully.

The issue, unfortunately, doesn't happen consistently, so I don't have a reproducible case. I will describe the steps once I have a way to reproduce.

Thanks in advance!

**Comment by FZambia** [comment]
@foobargeez thanks for report, what Centrifugo engine do you use - Memory or Redis?

**Comment by foobargeez** [comment]
Memory (at the moment).

**Comment by FZambia** [comment]
The code in examples written in synchronous style. In synchronous code it's hard to restart application state from scratch after subscription errors like this. Because program flow goes forward and client can't step back. Maybe event-driven approach is better for this? Just made a gist to demonstrate:

https://gist.github.com/FZambia/9d9f3ed31897fd6736c9cd6a7ff7ad0d

This allows to restart subscription after error occurred.

**Comment by FZambia** [comment]
Also maybe sth like this?

```
	c := centrifuge.New(wsURL, creds, events, centrifuge.DefaultConfig())

	var sub *centrifuge.Sub

	for {
		err := c.Connect()
		if err != nil {
			log.Fatalln(err)
		}

		subEvents := centrifuge.NewSubEventHandler()
		subHandler := &subEventHandler{}
		subEvents.OnMessage(subHandler)
		subEvents.OnSubscribeSuccess(subHandler)
		subEvents.OnUnsubscribe(subHandler)

		sub, err = c.Subscribe("public:chat", subEvents)
		if err != nil {
			c.Disconnect()
			continue
		}
		break
	}

        // Do sth this subscription...
```

**Comment by FZambia** [comment]
Merged branch with SubscribeAsync method to subscribe asynchronously, example [here](https://github.com/centrifugal/centrifuge-mobile/blob/master/examples/go/subscribe_async.go)
